# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy the project files
COPY . /app

# Install pip dependencies and build package without running scripts
RUN pip install --no-cache-dir .

# Expose any required port if applicable (optional)
# EXPOSE 8080

# Run the MCP server
CMD ["mcp"]
